Fix AttributeError after RatbagdButton.button was removed
AttributeError: 'RatbagdButton' object has no attribute 'button'

Introduced in 7f54cdc3f477f2f78bf100148aedaf02baf10e3b

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>